name: Checking 03-counter-app
on:
  push:
    branches: [master]
    paths:
    - 03-counter-app/src/**
    - 03-counter-app/package.json
    - 03-counter-app/package-lock.json
    

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: WolfYe98/ReactCursoUdemy
          path: 03-counter-app
      - name: install dependencies
        working-directory: ./03-counter-app
        run: npm install
      - name: run tests
        working-directory: ./03-counter-app
        run: npm test
